### ISSUE TITLE
System Message: ERROR/3 (<string>, line 18) Unknown directive type "toctree".

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/datagrepper#537]
It seems that the rst formatting is messed up on the [index page of datagrepper](https://apps.fedoraproject.org/datagrepper/). The text is readable, but it doesn't look good.

I noticed that the docs are in rst format, but they seem to have issue with toctree element on the actual page. [Here](https://github.com/fedora-infra/datagrepper/blob/develop/datagrepper/docs/index.rst) is the document in question.

**Comment by novicejava1** [comment]
HI, 

As per my understanding it seems the datagrepper/app.py is using docutils to generate the html docs from the rst docs. But docutils does not support the directive type "toctree" due to which there is a system error below the "Table of Contents" section
```
$ docutils index.rst index.html
index.rst:18: (ERROR/3) Unknown directive type "toctree".

.. toctree::
   :maxdepth: 2
   :caption: Contributor Guide

   contributing
```
If i generate the html docs using sphinx from datagrepper/docs folder under _build/html and launch the index.html the error does not occur.

Looks like we need to utilize sphinx to generate the html docs from the rst docs.
